# Generated by Django 6.0.6 on 2026-07-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=20)),
                ('screen_time', models.CharField(blank=True, max_length=20, null=True)),
                ('has_report', models.BooleanField(default=False)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('haiku', models.TextField()),
                ('reflection', models.TextField()),
                ('action', models.TextField()),
                ('pledge', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
