# Generated by Django 6.0.6 on 2026-07-29 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_digitalsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('why_it_matters', models.TextField(max_length=800)),
                ('current_focus', models.CharField(blank=True, max_length=200)),
                ('progress_unit', models.CharField(max_length=80)),
                ('weekly_target', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('preferred_days', models.JSONField(blank=True, default=list)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('minimum', 'Minimum'), ('standard', 'Standard'), ('deep', 'Deep')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('progress_value', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.usergoal')),
            ],
            options={
                'ordering': ['duration_minutes'],
            },
        ),
        migrations.AddConstraint(
            model_name='usergoal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'active')), fields=('user',), name='one_active_primary_goal_per_user'),
        ),
        migrations.AddConstraint(
            model_name='usergoal',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_target__gt', 0)), name='goal_weekly_target_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='goalaction',
            constraint=models.UniqueConstraint(fields=('goal', 'size'), name='one_action_size_per_goal'),
        ),
        migrations.AddConstraint(
            model_name='goalaction',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='goal_action_duration_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='goalaction',
            constraint=models.CheckConstraint(condition=models.Q(('progress_value__gt', 0)), name='goal_action_progress_gt_zero'),
        ),
    ]
