# Generated by Django 6.0.6 on 2026-08-01 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usergoal_goalaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_title', models.CharField(max_length=200)),
                ('action_size', models.CharField(choices=[('minimum', 'Minimum'), ('standard', 'Standard'), ('deep', 'Deep')], max_length=20)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('progress_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('progress_unit', models.CharField(max_length=80)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momentum_entries', to='core.goalaction')),
                ('digital_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='momentum_entry', to='core.digitalsummary')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momentum_entries', to='core.usergoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentum_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='momentum_duration_gt_zero'), models.CheckConstraint(condition=models.Q(('progress_value__gt', 0)), name='momentum_progress_gt_zero')],
            },
        ),
    ]
