# Generated by Django 6.0.6 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_momentum_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalsummary",
            name="goal_rescue_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
