# Generated by Django 6.0.6 on 2026-08-19 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_goalrescueoutcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='digitalsummary',
            index=models.Index(fields=['user', '-created_at'], name='summary_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='goalrescueoutcome',
            index=models.Index(fields=['user', '-shown_at'], name='rescue_user_shown_idx'),
        ),
        migrations.AddIndex(
            model_name='momentumentry',
            index=models.Index(fields=['user', '-completed_at'], name='momentum_user_done_idx'),
        ),
        migrations.AddIndex(
            model_name='postcard',
            index=models.Index(fields=['user', '-created_at'], name='postcard_user_created_idx'),
        ),
    ]
