# Generated by Django 6.0.6 on 2026-08-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_digitalsummary_summary_user_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsummary',
            name='app_usage',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_momentum_period',
            field=models.CharField(choices=[('all', 'All time'), ('week', 'This week'), ('month', 'This month'), ('30days', 'Last 30 days')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_skipped_rescue_statistics',
            field=models.BooleanField(default=True),
        ),
    ]
