# Generated by Django 6.0.6 on 2026-08-19 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_digitalsummary_app_usage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsummary',
            name='mobile_analytics_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='digitalsummary',
            name='mobile_assessment_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_daily_screen_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_actionable_inputs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_detailed_mobile_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_interaction_metrics',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ActionableInputFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_id', models.CharField(max_length=80)),
                ('input_type', models.CharField(max_length=40)),
                ('outcome', models.CharField(choices=[('helpful', 'Helpful'), ('used', 'Used this input'), ('not_useful', 'Not useful')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digital_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionable_input_feedback', to='core.digitalsummary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionable_input_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'input_type', 'outcome'], name='input_feedback_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'digital_summary', 'input_id'), name='one_feedback_per_actionable_input')],
            },
        ),
    ]
