# Generated by Django 6.0.6 on 2026-08-19 12:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_digitalsummary_mobile_analytics_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=80, unique=True)),
                ('last_run_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='in_app_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_reminder_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminders_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stale_device_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_review_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify', 'Verify'), ('change', 'Change')], max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('device_model', models.CharField(blank=True, max_length=80)),
                ('os_version', models.CharField(blank=True, max_length=32)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_rotated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent_version', models.CharField(max_length=16)),
                ('consent_accepted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=24)),
                ('last_sync_error_code', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_report_id', models.CharField(max_length=120)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_report', to='core.digitalsummary')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.userdevice')),
            ],
        ),
        migrations.CreateModel(
            name='DevicePairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'consumed_at'], name='pairing_expiry_idx')],
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=400)),
                ('link', models.CharField(blank=True, max_length=240)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='notification_user_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='unique_notification_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('goal', 'Goal action'), ('weekly', 'Weekly Review'), ('deadline', 'Goal deadline'), ('resume', 'Resume paused goal'), ('target', 'Screen-time target'), ('device', 'Device sync stale')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=400)),
                ('link', models.CharField(blank=True, max_length=240)),
                ('due_at', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'due_at'], name='reminder_due_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreenTimeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('overall', 'Overall'), ('app', 'App'), ('category', 'Category')], max_length=16)),
                ('key', models.CharField(blank=True, max_length=160)),
                ('daily_minutes', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'target_type', 'enabled'], name='target_user_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_type', 'key'), name='unique_user_screen_target'), models.CheckConstraint(condition=models.Q(('daily_minutes__gt', 0)), name='screen_target_minutes_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='security_user_event_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAppPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_app_name', models.CharField(max_length=160)),
                ('display_name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('Social', 'Social'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Productivity', 'Productivity'), ('Communication', 'Communication'), ('Games', 'Games'), ('Browser', 'Browser'), ('Utilities', 'Utilities'), ('Health/Fitness', 'Health/Fitness'), ('Finance', 'Finance'), ('Work', 'Work'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=32)),
                ('purpose', models.CharField(choices=[('Goal aligned', 'Goal aligned'), ('Useful', 'Useful'), ('Neutral', 'Neutral'), ('Distracting', 'Distracting'), ('Mixed', 'Mixed'), ('Unknown', 'Unknown')], default='Unknown', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_preferences', to='core.usergoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['user', 'normalized_app_name'], name='app_pref_user_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'normalized_app_name'), name='unique_user_app_preference')],
            },
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active', '-last_successful_sync_at'], name='device_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceanalyticsreport',
            index=models.Index(fields=['device', '-received_at'], name='device_report_received_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceanalyticsreport',
            constraint=models.UniqueConstraint(fields=('device', 'device_report_id'), name='unique_device_report_id'),
        ),
    ]
