# Generated by Django 6.0.6 on 2026-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_maintenancejobrun_userprofile_device_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsummary',
            name='ingestion_source',
            field=models.CharField(choices=[('legacy', 'Legacy or unknown'), ('manual', 'Manual entry'), ('screenshot', 'Screenshot import'), ('file_import', 'CSV or text import'), ('device_sync', 'Device sync')], default='legacy', max_length=24),
        ),
        migrations.AddField(
            model_name='digitalsummary',
            name='total_basis',
            field=models.CharField(choices=[('legacy_unknown', 'Legacy or unknown'), ('official_reported', 'Official reported total'), ('user_entered', 'User-entered total'), ('device_reported', 'Device-reported total'), ('recognized_app_sum', 'Recognized-app sum')], default='legacy_unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='digitalsummary',
            name='was_user_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
